config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'welcome#index'

  resources :order_items

  resources :groups do
    resources :memberships, expect: [:edit, :update]

    resources :orders
  end

  post "/groups/:group_id/memberships/:id/set_admin",       to: "memberships#set_admin",        as: "group_membership_set_admin"
  post "/groups/:group_id/memberships/:id/remove_admin",    to: "memberships#remove_admin",     as: "group_membership_remove_admin"

  resources :restaurants

  devise_for :users
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :memberships, dependent: :destroy
  has_many :users, through: :memberships
  has_many :orders, dependent: :destroy

  validates :name, presence: true, length: { maximum: 255 }, uniqueness: true
  validates :description, length: { maximum: 500 }

  def admin?(user)
    membership = self.has_membership(user)
    membership.admin if membership
  end

  def set_admin(user) # TODO przerobic jakos ladniej
    membership = self.has_membership(user)
    membership.update(admin: true) if membership
  end

  def has_membership(user)
    self.memberships.find_by(user_id: user.id)
  end

  def available_users
    ids = Membership.where(group_id: id).pluck(:user_id)
    User.where('id not in (?)', ids)
  end

end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :user
  belongs_to :group

  validates :user_id, uniqueness: { scope: :group_id }
  validates :user, :group, presence: true

  def set_admin(user)
    user.update(admin: true) if self.admin || self.user.admin
  end
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action :set_membership, only: [:show, :set_admin, :remove_admin, :destroy]
  before_action :set_group
  before_action :authenticate_user!
  before_action :authorize_user, only: [:index]
  before_action :authorize_admin, except: [:index]

  rescue_from Pundit::NotAuthorizedError do
    flash[:error] = "Access denied"
    redirect_to group_memberships_path(@group)
  end

  def index
    @memberships = @group.memberships
  end

  def show
    unless @group.memberships.include? @membership
      flash[:error] = "Requested membership not found"
      redirect_to group_memberships_path(@group)
    end
  end

  def new
    @users = @group.available_users
  end


  def create
    if params[:user_id]
      @group.user_ids += params[:user_ids]

      respond_to do |format|
        format.html { redirect_to group_memberships_path, notice: 'Memberships was successfully created.' }
      end
    else
      redirect_to group_memberships_path(@group)
    end
  end

  def set_admin
    @group.has_membership(current_user).set_admin(@membership)
    redirect_to group_memberships_path(@group)
  end

  def remove_admin
    authorize @membership, :remove_admin?
    @membership.update(admin: false)
    redirect_to group_memberships_path(@group)
  end

  def destroy
    @membership.destroy
    respond_to do |format|
      format.html { redirect_to group_memberships_url(@group), notice: 'Membership was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def authorize_admin
      authorize @group, :admin?
    end

    def authorize_user
      authorize @group, :user?
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_membership
      @membership = Membership.find(params[:id])
    end

    def set_group
      @group = Group.find(params[:group_id])
    end
end

app/views/memberships/index.html.erb
<% if notice %>
    <div class="alert alert-success" role="alert">
        <strong><%= notice %></strong>
    </div>
<% end %>


<h1>Użytkownicy grupy </h1>
<h3><%= @group.name %></h3>

<table class="table table-striped">

  <thead>
    <tr>
      <th>Użytkownik</th>
      <th>Admin?</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @memberships.each do |membership| %>
      <tr>
        <td><b><%= membership.user.email %></b></td>
        <td>
          <% if policy(@group).admin? %>
            <% if membership.admin %>
              <%= link_to 'TAK', group_membership_remove_admin_path(@group, membership.id), method: :post, class: 'btn btn-success', data: { confirm: 'Usunąć uprawnienia?' } %>
            <% else %>
              <%= link_to 'NIE', group_membership_set_admin_path(@group, membership.id), method: :post, class: 'btn btn-danger', data: { confirm: 'Nadać uprawnienia?' } %>
            <% end %>
          <% else %>
            <% if membership.admin %>
              <%= button_tag 'TAK', disabled: true, class: 'btn btn-success' %>
            <% else %>
              <%= button_tag 'NIE', disabled: true, class: 'btn btn-danger' %>
            <% end %>
          <% end %>
        </td>
        <td>
          <% if policy(@group).admin? %>
            <%= link_to 'Usuń', group_membership_path(@group, membership.id), method: :delete, class: 'btn btn-danger', data: { confirm: 'Czy jesteś pewien?' } %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>

</table>

<% if policy(@group).admin? %>
  <%= link_to 'Dodaj użytkowników', new_group_membership_path(@group), class: 'btn btn-primary' %>
<% end %>
<%= link_to 'Powróć', @group, class: 'btn btn-default' %>

app/views/memberships/new.html.erb
<h1>Dodaj użytkowników</h1>

<%= form_tag group_memberships_path(@group), method: :post do %>
    <table class="table table-striped">

        <thead>
            <tr>
                <th>Użytkownik</th>
            </tr>
        </thead>

        <tbody>
            <% @users.each do |user| %>
                <tr>
                    <td>
                        <input id="user_<%= user.id %>" type="checkbox" name="user_ids[]" value="<%= user.id %>">
                        <label for="user_<%= user.id %>"><%= user.email %></label>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
    <div class="actions">
        <%= submit_tag "Dodaj", class: 'btn btn-success' %>
        <%= link_to 'Idź dalej', group_memberships_path(@group), class: 'btn btn-default' %>
    </div>
<% end %>