config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'welcome#index'

  resources :order_items

  resources :groups do
    resources :memberships, expect: [:edit, :update]

    resources :orders
  end

  post "/groups/:group_id/memberships/:id/set_admin",       to: "memberships#set_admin",        as: "group_membership_set_admin"
  post "/groups/:group_id/memberships/:id/remove_admin",    to: "memberships#remove_admin",     as: "group_membership_remove_admin"

  resources :restaurants

  devise_for :users
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :memberships, dependent: :destroy
  has_many :users, through: :memberships
  has_many :orders, dependent: :destroy

  validates :name, presence: true, length: { maximum: 255 }, uniqueness: true
  validates :description, length: { maximum: 500 }

  def admin?(user)
    membership = self.has_membership(user)
    membership.admin if membership
  end

  def set_admin(user) # TODO przerobic jakos ladniej
    membership = self.has_membership(user)
    membership.update(admin: true) if membership
  end

  def has_membership(user)
    self.memberships.find_by(user_id: user.id)
  end

  def available_users
    ids = Membership.where(group_id: id).pluck(:user_id)
    User.where('id not in (?)', ids)
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :authorize_user, only: [:show]
  before_action :authorize_admin, only: [:edit, :update, :destroy]

  rescue_from Pundit::NotAuthorizedError do
    flash[:error] = "Dostęp zabroniony"
    redirect_to groups_path
  end

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @orders = @group.orders
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        @group.users << current_user
        @group.set_admin(current_user)
        format.html { redirect_to new_group_membership_path(@group), notice: 'Grupa pomyślnie stworzona.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Grupa pomyślnie zedytowana.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Grupa pomyślnie usunięta.' }
      format.json { head :no_content }
    end
  end

  private
    def authorize_admin
      authorize @group, :admin?
    end

    def authorize_user
      authorize @group, :user?
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :description)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <% @group.errors.full_messages.each do |message| %>
      <div class="alert alert-danger" role="alert"><%= message %></div>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= f.label :name, "Nazwa grupy" %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description, "Krótki opis" %><br>
    <%= f.text_area :description, class: 'form-control', cols: "30", rows: "10" %>
  </div>
  <div class="actions">
    <%= f.submit "Potwierdź", class: 'btn btn-success' %>
    <%= link_to 'Powróć', groups_path, class: 'btn btn-default' %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Edytuj grupę</h1>

<%= render 'form' %>

app/views/groups/index.html.erb
<% if notice %>
    <div class="alert alert-success" role="alert">
        <strong><%= notice %></strong>
    </div>
<% end %>
<h1>Lista grup</h1>


<table class="table table-striped">

  <thead>
    <tr>
      <th>Nazwa</th>
      <th>Opis</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><b><%= group.name %></b></td>
        <td><%= truncate group.description, length: 100 %></td>
        <td>
          <% if policy(group).user? %>
            <%= link_to 'Pokaż', group, class: 'btn btn-success' %></td>
          <% end %>
        </td>
        <td>
          <% if policy(group).admin? %>
            <%= link_to 'Edytuj', edit_group_path(group), class: 'btn btn-info' %>
          <% end %>
        </td>
        <td>
          <% if policy(group).admin? %>
            <%= link_to 'Usuń', group, method: :delete, class: 'btn btn-danger', data: { confirm: 'Czy jesteś pewien?' } %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>

</table>

<%= link_to 'Nowa grupa', new_group_path, class: 'btn btn-primary' %>

app/views/groups/new.html.erb
<h1>Nowa grupa</h1>

<%= render 'form' %>

app/views/groups/show.html.erb
<% if notice %>
    <div class="alert alert-success" role="alert">
        <strong><%= notice %></strong>
    </div>
<% end %>

<h2><%= @group.name %></h2>
<p><%= @group.description %></p>

<div>
    <%= link_to 'Dodaj zamówienie', new_group_order_path(@group), class: 'btn btn-success' %>
</div>

<% if @orders.any? %>
    <table class="table table-striped">

      <thead>
        <tr>
          <th>Restauracja</th>
        </tr>
      </thead>

      <tbody>
        <% @orders.each do |order| %>
          <tr>
            <td><strong><%= order.restaurant.name %></strong></td>
          </tr>
        <% end %>
      </tbody>

    </table>
<% end %>

<div style="margin-top: 10px;">
<%= link_to 'Lista użytkowników', group_memberships_path(@group), class: 'btn btn-success' %>
<%= link_to 'Edytuj', edit_group_path(@group), class: 'btn btn-primary' %>
<%= link_to 'Powróć', groups_path, class: 'btn btn-default' %>
</div>