config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'welcome#index'

  resources :order_items

  resources :groups do
    resources :memberships, expect: [:edit, :update]

    resources :orders
  end

  post "/groups/:group_id/memberships/:id/set_admin",       to: "memberships#set_admin",        as: "group_membership_set_admin"
  post "/groups/:group_id/memberships/:id/remove_admin",    to: "memberships#remove_admin",     as: "group_membership_remove_admin"

  resources :restaurants

  devise_for :users
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :user
  belongs_to :order

  validates :user_id, :order_id, :name, :quantity, :price, presence: true
  validates :name, length: { maximum: 255 }
  validates :quantity, :price, numericality: true
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  before_action :set_order_item, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /order_items
  # GET /order_items.json
  def index
    @order_items = OrderItem.all
  end

  # GET /order_items/1
  # GET /order_items/1.json
  def show
  end

  # GET /order_items/new
  def new
    @order_item = OrderItem.new
  end

  # GET /order_items/1/edit
  def edit
  end

  # POST /order_items
  # POST /order_items.json
  def create
    @order_item = OrderItem.new(order_item_params)

    respond_to do |format|
      if @order_item.save
        format.html { redirect_to @order_item, notice: 'Order item was successfully created.' }
        format.json { render :show, status: :created, location: @order_item }
      else
        format.html { render :new }
        format.json { render json: @order_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /order_items/1
  # PATCH/PUT /order_items/1.json
  def update
    respond_to do |format|
      if @order_item.update(order_item_params)
        format.html { redirect_to @order_item, notice: 'Order item was successfully updated.' }
        format.json { render :show, status: :ok, location: @order_item }
      else
        format.html { render :edit }
        format.json { render json: @order_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /order_items/1
  # DELETE /order_items/1.json
  def destroy
    @order_item.destroy
    respond_to do |format|
      format.html { redirect_to order_items_url, notice: 'Order item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_item
      @order_item = OrderItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_item_params
      params.require(:order_item).permit(:name, :quantity, :price)
    end
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/views/order_items/_form.html.erb
<%= form_for(@order_item) do |f| %>
  <% if @order_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order_item.errors.count, "error") %> prohibited this order_item from being saved:</h2>

      <ul>
      <% @order_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/order_items/edit.html.erb
<h1>Editing Order Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @order_item %> |
<%= link_to 'Back', order_items_path %>

app/views/order_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Order Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Quantity</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @order_items.each do |order_item| %>
      <tr>
        <td><%= order_item.name %></td>
        <td><%= order_item.quantity %></td>
        <td><%= order_item.price %></td>
        <td><%= link_to 'Show', order_item %></td>
        <td><%= link_to 'Edit', edit_order_item_path(order_item) %></td>
        <td><%= link_to 'Destroy', order_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order item', new_order_item_path %>

app/views/order_items/new.html.erb
<h1>New Order Item</h1>

<%= render 'form' %>

<%= link_to 'Back', order_items_path %>

app/views/order_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @order_item.name %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @order_item.quantity %>
</p>

<p>
  <strong>Price:</strong>
  <%= @order_item.price %>
</p>

<%= link_to 'Edit', edit_order_item_path(@order_item) %> |
<%= link_to 'Back', order_items_path %>