config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'welcome#index'

  resources :order_items

  resources :groups do
    resources :memberships, expect: [:edit, :update]

    resources :orders
  end

  post "/groups/:group_id/memberships/:id/set_admin",       to: "memberships#set_admin",        as: "group_membership_set_admin"
  post "/groups/:group_id/memberships/:id/remove_admin",    to: "memberships#remove_admin",     as: "group_membership_remove_admin"

  resources :restaurants

  devise_for :users
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>FoodBook</title>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <nav class="navbar navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "FoodBook", root_path, class: 'navbar-brand' %>
        </div>

        <div id="navbar" class="navbar-collapse collapse<%= ' navbar-right' unless user_signed_in? %>">
          <% if user_signed_in? %>
            <ul class="nav navbar-nav">
              <li>
                <%= link_to "Grupy", groups_path %>
              </li>
              <li>
                <%= link_to "Restauracje", restaurants_path %>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Więcej <span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                  <li><%= link_to('Wyloguj', destroy_user_session_path, :method => :delete) %></li>
                </ul>
              </li>
            </ul>
          <% else %>
            <%= form_for :user, url: session_path(:user), html: { class: 'navbar-form navbar-right' } do |f| %>
              <div class="form-group">
                <%= f.text_field :email, placeholder: 'Email', class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.password_field :password, placeholder: 'Hasło', class: 'form-control' %>
              </div>
              <%= f.submit 'Zaloguj się', class: 'btn btn-success' %>
              <%= link_to 'Zarejestruj się', new_user_registration_path, class: 'btn btn-primary' %>
            <% end %>
          <% end %>
        </div><!--/.navbar-collapse -->
      </div>
    </nav>

    <div class="container">
        <%= yield %>
    </div> <!-- /container -->

  </body>
</html>